name: 'Tieba Sign'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 22 * * *'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v4
      - name: 'Set python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
          SENDKEY: ${{ secrets.SENDKEY }}
        run: python main.py
